---
- name: Setup Zabbix Agent2 on Ubuntu 22.04
  hosts: all
  become: true
  vars:
    zabbix_release_deb_url: "https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu22.04_all.deb"
    zabbix_release_deb_filename: "/tmp/zabbix-release_latest_7.2+ubuntu22.04_all.deb"
    zabbix_conf_path: "/etc/zabbix/zabbix_agent2.conf"
    zabbix_service_name: "zabbix-agent2"
    zabbix_server_domain: "udon04"

  tasks:
    - name: Download Zabbix release .deb file
      get_url:
        url: "{{ zabbix_release_deb_url }}"
        dest: "{{ zabbix_release_deb_filename }}"

    - name: Install Zabbix release package
      apt:
        deb: "{{ zabbix_release_deb_filename }}"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix Agent2
      apt:
        name: zabbix-agent2
        state: present

    - name: Resolve Zabbix server domain to IP
      shell: "getent hosts {{ zabbix_server_domain }} | awk '{ print $1 }'"
      register: zabbix_server_ip_result
      changed_when: false
      failed_when: zabbix_server_ip_result.stdout == ""

    - name: Set fact for resolved Zabbix server IP
      set_fact:
        zabbix_server_ip: "{{ zabbix_server_ip_result.stdout }}"

    - name: Update 'Server=' in config
      lineinfile:
        path: "{{ zabbix_conf_path }}"
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        create: yes

    - name: Update 'ServerActive=' in config
      lineinfile:
        path: "{{ zabbix_conf_path }}"
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"
        create: yes

    - name: Ensure Zabbix Agent2 is started and enabled
      systemd:
        name: "{{ zabbix_service_name }}"
        state: restarted
        enabled: yes
