---
- name: Configure rsyslog to send logs to four syslog servers (UDP)
  hosts: all
  become: true
  tasks:
    - name: Ensure rsyslog.conf contains syslog server IPs
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^(\*\.{1,2})'
        line: "{{ item }}"
        create: yes
      with_items:
        - "*.* @172.29.139.4:514"    # syslog01 UDP (IP 1)
        - "*.* @172.29.128.90:514"   # syslog01 UDP (IP 2)
        - "*.* @172.29.137.217:514"  # syslog02 UDP (IP 1)
        - "*.* @172.29.135.189:514"  # syslog02 UDP (IP 2)
      notify: restart rsyslog

  handlers:
    - name: restart rsyslog
      systemd:
        name: rsyslog
        state: restarted
